[callback] bool OnGameModeInit();
[callback] bool OnGameModeExit();
[callback] bool OnPlayerConnect(int playerid);
[callback] bool OnPlayerDisconnect(int playerid, int reason);
[callback] bool OnPlayerSpawn(int playerid);
[callback] bool OnPlayerDeath(int playerid, int killerid, int reason);
[callback] bool OnVehicleSpawn(int vehicleid);
[callback] bool OnVehicleDeath(int vehicleid, int killerid);
[callback] bool OnPlayerText(int playerid, string text);
[callback] bool OnPlayerCommandText(int playerid, string cmdtext);
[callback] bool OnPlayerRequestClass(int playerid, int classid);
[callback] bool OnPlayerEnterVehicle(int playerid, int vehicleid, bool ispassenger);
[callback] bool OnPlayerExitVehicle(int playerid, int vehicleid);
[callback] bool OnPlayerStateChange(int playerid, int newstate, int oldstate);
[callback] bool OnPlayerEnterCheckpoint(int playerid);
[callback] bool OnPlayerLeaveCheckpoint(int playerid);
[callback] bool OnPlayerEnterRaceCheckpoint(int playerid);
[callback] bool OnPlayerLeaveRaceCheckpoint(int playerid);
[callback] bool OnRconCommand(string cmd);
[callback] bool OnPlayerRequestSpawn(int playerid);
[callback] bool OnObjectMoved(int objectid);
[callback] bool OnPlayerObjectMoved(int playerid, int objectid);
[callback] bool OnPlayerPickUpPickup(int playerid, int pickupid);
[callback] bool OnVehicleMod(int playerid, int vehicleid, int componentid);
[callback] bool OnEnterExitModShop(int playerid, int enterexit, int interiorid);
[callback] bool OnVehiclePaintjob(int playerid, int vehicleid, int paintjobid);
[callback, badref(false)] bool OnVehicleRespray(int playerid, int vehicleid, int color1, int color2);
[callback] bool OnVehicleDamageStatusUpdate(int vehicleid, int playerid);
[callback] bool OnUnoccupiedVehicleUpdate(int vehicleid, int playerid, int passenger_seat, float new_x, float new_y, float new_z, float vel_x, float vel_y, float vel_z);
[callback] bool OnPlayerSelectedMenuRow(int playerid, int row);
[callback] bool OnPlayerExitedMenu(int playerid);
[callback] bool OnPlayerInteriorChange(int playerid, int newinteriorid, int oldinteriorid);
[callback] bool OnPlayerKeyStateChange(int playerid, int newkeys, int oldkeys);
[callback] bool OnRconLoginAttempt(string ip, string password, bool success);
[callback] bool OnPlayerUpdate(int playerid);
[callback] bool OnPlayerStreamIn(int playerid, int forplayerid);
[callback] bool OnPlayerStreamOut(int playerid, int forplayerid);
[callback] bool OnVehicleStreamIn(int vehicleid, int forplayerid);
[callback] bool OnVehicleStreamOut(int vehicleid, int forplayerid);
[callback] bool OnActorStreamIn(int actorid, int forplayerid);
[callback] bool OnActorStreamOut(int actorid, int forplayerid);
[callback] bool OnDialogResponse(int playerid, int dialogid, int response, int listitem, string inputtext);
[callback] bool OnPlayerTakeDamage(int playerid, int issuerid, float amount, int weaponid, int bodypart);
[callback] bool OnPlayerGiveDamage(int playerid, int damagedid, float amount, int weaponid, int bodypart);
[callback] bool OnPlayerGiveDamageActor(int playerid, int damaged_actorid, float amount, int weaponid, int bodypart);
[callback] bool OnPlayerClickMap(int playerid, float fX, float fY, float fZ);
[callback] bool OnPlayerClickTextDraw(int playerid, int clickedid);
[callback] bool OnPlayerClickPlayerTextDraw(int playerid, int playertextid);
[callback] bool OnIncomingConnection(int playerid, string ip_address, int port);
[callback] bool OnTrailerUpdate(int playerid, int vehicleid);
[callback] bool OnVehicleSirenStateChange(int playerid, int vehicleid, int newstate);
[callback] bool OnPlayerClickPlayer(int playerid, int clickedplayerid, int source);
[callback] bool OnPlayerEditObject(int playerid, bool playerobject, int objectid, int response, float fX, float fY, float fZ, float fRotX, float fRotY, float fRotZ);
[callback] bool OnPlayerEditAttachedObject(int playerid, int response, int index, int modelid, int boneid, float fOffsetX, float fOffsetY, float fOffsetZ, float fRotX, float fRotY, float fRotZ, float fScaleX, float fScaleY, float fScaleZ);
[callback] bool OnPlayerSelectObject(int playerid, int type, int objectid, int modelid, float fX, float fY, float fZ);
[callback] bool OnPlayerWeaponShot(int playerid, int weaponid, int hittype, int hitid, float fX, float fY, float fZ);
